config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :aimes
  resources :eyes
  resources :vues
  resources :demandes
  resources :locations
  resources :towns
  root 'places#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :places do
    get :like
    get :dislike
    get :save_comments
  end 
  get 'ventes', to: 'places#ventes'
  get 'rents', to: 'places#locations'
  get 'auberge', to: 'places#auberge'
  get 'shared', to: 'places#shared'
  get 'guide', to: 'places#guide'
  get 'courtiers', to: 'places#courtiers'
  get 'shop', to: 'places#shop'
  get 'pubs', to: 'places#pubs'
  get 'admin', to: 'places#admin'
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
      puts "admin"
    elsif user.id==nil
      #Un guest non connecté
      can [:read, :create], User
      can [:read, :like, :dislike], Place
      can [:read, :create], Demande
      puts "guest"  
    else
      # Un proprio
      can :manage, Place, uid: user.id
      can :create, Place
      can :update, User, id: user.id
      can :read, User
      can [:read, :like, :dislike], Place
      can [:read, :create], Demande
      puts "proprio"
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/aime.rb
class Aime < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/demande.rb
class Demande < ApplicationRecord
end

app/models/eye.rb
class Eye < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
    has_attached_file :picture1, validate_media_type: false, default_url: "house.png"
    has_attached_file :picture2, validate_media_type: false, default_url: "house.png"
    has_attached_file :picture3, validate_media_type: false, default_url: "house.png"
    has_attached_file :picture4, validate_media_type: false, default_url: "house.png"
    has_attached_file :picture5, validate_media_type: false, default_url: "house.png"
    validates_attachment :picture1, :picture2, :picture3, :picture4, :picture5
    do_not_validate_attachment_file_type :picture1, :picture2, :picture3, :picture4, :picture5
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/town.rb
class Town < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]
  has_attached_file :profile, validate_media_type: false, default_url: "default.jpg"
  validates_attachment :profile
  do_not_validate_attachment_file_type :profile


  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.uid = auth.uid
      user.provider = auth.provider
      puts(auth.info.first_name)
      #user.name = auth.info.name    assuming the user model has a name
      #user.image = auth.info.image  assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  
end

app/controllers/demandes_controller.rb
class DemandesController < ApplicationController
  before_action :set_demande, only: [:show, :edit, :update, :destroy]

  # GET /demandes
  # GET /demandes.json
  def index
    @demandes = Demande.all
  end

  # GET /demandes/1
  # GET /demandes/1.json
  def show
  end

  # GET /demandes/new
  def new
    @demande = Demande.new
  end

  # GET /demandes/1/edit
  def edit
  end

  # POST /demandes
  # POST /demandes.json
  def create
    @demande = Demande.new(demande_params)

    respond_to do |format|
      if @demande.save
        format.html { redirect_to demandes_path, notice: 'Demande was successfully created.' }
        format.json { render :show, status: :created, location: @demande }
      else
        format.html { render :new }
        format.json { render json: @demande.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demandes/1
  # PATCH/PUT /demandes/1.json
  def update
    respond_to do |format|
      if @demande.update(demande_params)
        format.html { redirect_to @demande, notice: 'Demande was successfully updated.' }
        format.json { render :show, status: :ok, location: @demande }
      else
        format.html { render :edit }
        format.json { render json: @demande.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demandes/1
  # DELETE /demandes/1.json
  def destroy
    @demande.destroy
    respond_to do |format|
      format.html { redirect_to demandes_url, notice: 'Demande was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demande
      @demande = Demande.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demande_params
      params.require(:demande).permit(:description)
    end
end

app/helpers/aimes_helper.rb
module AimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/demandes_helper.rb
module DemandesHelper
end

app/helpers/eyes_helper.rb
module EyesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/helpers/vues_helper.rb
module VuesHelper
end

app/views/demandes/_form.html.erb
<%= simple_form_for(@demande) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/demandes/edit.html.erb
<h1>Editing Demande</h1>

<%= render 'form', demande: @demande %>

<%= link_to 'Show', @demande %> |
<%= link_to 'Back', demandes_path %>

app/views/demandes/index.html.erb
<br>
<div class="container" align="center">  
  <h1>  Demandes formulées par nos clients</h1>
  <p> Si le formulaire de recherche ne vous permet pas de trouver votre bonheur sur ce site, n'hésitez pas à formuler une demande
    la plus précise possible aux centaines de courtiers avec lesquels nous collaborons. Et n'oubliez surtout pas d'indiquer votre 
    numéro de téléphone ainsi que la somme dont vous disposez <i class="fa fa-smile-o" aria-hidden="true"></i>

  </p>
      <%= simple_form_for(Demande.new) do |f| %>
        <%= f.error_notification %>
            <div class="form-group has-feedback col-md-2">
              <div class="icon"><i class="pe-7s-pen"></i></div>
            </div>
            <div class="form-group has-feedback col-md-10">
              <div class="form-inputs">
                <%= f.text_area :description, label:false, class:'form-control', placeholder:'Bonjour tout le monde, je m\'appelle Mamadou. Je cherche ...'  %>
              </div>
            </div>
        
        
        <br>
        <div class="row">
            <div class="form-actions">
              <%= f.button :submit, "Formulez votre demande", class:'btn btn-success' %>
            </div>
        </div>
        
      <% end %>
</div>
<br>
<hr>  

<div class="container">
  <% @demandes.each do |demande| %>
    <div class="container">
        <h5 class="posted"><i class="fa fa-clock-o"></i> <%= demande.created_at.strftime("%d %b. %Y") +" "+ demande.created_at.strftime("%H:%M")  %></h5>
        <blockquote>  
          <p class="post__intro"> <%= demande.description %></p>
        </blockquote>
    </div>
    <hr>
  <% end %>
</div>

app/views/demandes/new.html.erb
<h1>New Demande</h1>

<%= render 'form', demande: @demande %>

<%= link_to 'Back', demandes_path %>

app/views/demandes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @demande.description %>
</p>

<%= link_to 'Edit', edit_demande_path(@demande) %> |
<%= link_to 'Back', demandes_path %>