config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :aimes
  resources :eyes
  resources :vues
  resources :demandes
  resources :locations
  resources :towns
  root 'places#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :places do
    get :like
    get :dislike
    get :save_comments
  end 
  get 'ventes', to: 'places#ventes'
  get 'rents', to: 'places#locations'
  get 'auberge', to: 'places#auberge'
  get 'shared', to: 'places#shared'
  get 'guide', to: 'places#guide'
  get 'courtiers', to: 'places#courtiers'
  get 'shop', to: 'places#shop'
  get 'pubs', to: 'places#pubs'
  get 'admin', to: 'places#admin'
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
    has_attached_file :picture1, validate_media_type: false, default_url: "house.png"
    has_attached_file :picture2, validate_media_type: false, default_url: "house.png"
    has_attached_file :picture3, validate_media_type: false, default_url: "house.png"
    has_attached_file :picture4, validate_media_type: false, default_url: "house.png"
    has_attached_file :picture5, validate_media_type: false, default_url: "house.png"
    validates_attachment :picture1, :picture2, :picture3, :picture4, :picture5
    do_not_validate_attachment_file_type :picture1, :picture2, :picture3, :picture4, :picture5
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
    @q = Place.search(params[:q])
    @neededPlaces = @q.result(distinct: true)
    @c = Category.all
  end
  def ventes
    @places = Place.all
  end
  def guide
  end
  def locations
    @places = Place.all
  end
  def shared
    @places = Place.all
  end
  def auberge
    @places = Place.all
  end
  def courtiers
    @users = User.all
    @q = User.search(params[:q])
    @court = @q.result(distinct: true)
  end
  def shop
    @owner=User.find(params[:type]);
    @ownedPlaces=Place.where(uid: @owner.id)
  end
  def pubs
    @pubPlaces=Place.where(uid: current_user.id)
  end
  def admin
    @pubPlaces=Place.where(uid: current_user.id)
  end

  # GET /places/1
  # GET /places/1.json
  def show
    e=Eye.new
    if current_user!=nil
      if Eye.exists?(viewer: current_user.id, viewee: @place.id)
      else
        e.viewer=current_user.id
        e.viewee=@place.id
        @place.views=@place.views+1
        e.save 
        @place.save
      end      
    else
        e.viewee=@place.id
        @place.views=@place.views+1
        e.save 
        @place.save
    end
    
  end

  def like
    @place=Place.find(params[:place_id])
    puts "somebody liked "+String(@place.id)+" ..."
    e=Aime.new
    if current_user!=nil
      if Aime.exists?(liker: current_user.id, liked: @place.id)
      else
        e.liker=current_user.id
        e.liked=@place.id
        @place.likes=@place.likes+1
        e.save 
        @place.save
      end      
    else
        e.liked=@place.id
        @place.likes=@place.likes+1
        e.save 
        @place.save
    end
  end

  def dislike
    @place=Place.find(params[:place_id])
    if current_user!=nil  
      Aime.where(liker: current_user.id, liked: @place.id).destroy_all
    end
    @place.likes = @place.likes - 1
    @place.save
  end

  
  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    @place.views=0
    @place.likes=0
    if @place.price==nil
      @place.price=0
    end
    @place.uid = current_user.id
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :categoryName, :price, :availability, :furnitures, :daily, :monthly, :picture1, :picture2, :picture3, :picture4, :picture5, :location, :forSale, :forRent, :shared, :auberge)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>
  <%= f.error_notification %>

  <div>
    <div class="form-group has-feedback col-md-6">
      <%= f.input :name, :label => "Titre" , placeholder:'Saisissez le nom de votre logement', :required => true %>
      </div>
      <div class="form-group has-feedback col-md-6">
      <%= f.input :price, :label => "Prix (en FCFA)" %>
    </div>
  </div>
  <div>
      <div class="form-group has-feedback col-md-2">
        Categorie du logement
        <%= f.collection_select :categoryName, Category.order(:name),:id,:name, {:include_blank=>true}, {:class=>'form-control', :label => "Catégorie logement", :required => true } %>
      </div>
      <div class="form-group has-feedback col-md-2">
        Emplacement
        <%= f.collection_select :location, Location.order(:name),:name,:name, {:include_blank=>true, :label => "Emplacement logement"}, {:class=>'form-control', :required => true } %>
      </div>
      <div class="form-group has-feedback col-md-1">
        <%= f.input :availability, :label => "Disponible", class:'form-control' %>
      </div>
      <div class="form-group has-feedback col-md-1">
        <%= f.input :furnitures, :label => "Meublé", class:'form-control' %>
      </div>
      <div class="form-group has-feedback col-md-1">
        <%= f.input :daily, :label => "Journalier", class:'form-control' %>
      </div>
      <div class="form-group has-feedback col-md-1">
        <%= f.input :monthly, :label => "Mensuel", class:'form-control' %>
      </div>
      <div class="form-group has-feedback col-md-1">
        <%= f.input :forSale, :label => "Vente", class:'form-control' %>
      </div>
      <div class="form-group has-feedback col-md-1">
        <%= f.input :forRent, :label => "A louer", class:'form-control' %>
      </div>
      <div class="form-group has-feedback col-md-1">
        <%= f.input :shared, :label => "Hotes", class:'form-control' %>
      </div>
      <div class="form-group has-feedback col-md-1">
        <%= f.input :auberge, :label => "Auberge", class:'form-control' %>
      </div>
  </div>
  </hr>
  <p></p>
  <label class='label label-warning'>Postez jusqu'à 5 photos du logement</label><p></p>
  <div class="form-group has-feedback col-md-12">
    <div class="form-group has-feedback col-md-4">
    <%= f.file_field :picture1, class:'form-control' %>
    </div>
    <div class="form-group has-feedback col-md-4">
    <%= f.file_field :picture2, class:'form-control' %>
    </div>
    <div class="form-group has-feedback col-md-4">
    <%= f.file_field :picture3, class:'form-control' %>
    </div>
  </div>
  <div class="form-group has-feedback col-md-12">
    <div class="form-group has-feedback col-md-6">
    <%= f.file_field :picture4, class:'form-control' %>
    </div>
    <div class="form-group has-feedback col-md-6">
    <%= f.file_field :picture5, class:'form-control' %>
    </div>
  </div>
    
  <div class="form-group has-feedback col-md-12">
    <div><%= f.text_area :description, :label => "Description", :required => true, class:'form-control', placeholder:'Décrivez votre logement autant que possible... (1000 mots)' %></div>    
  </div>
  <div class="form-group col-md-12">
    <%= f.button :submit, 'Publier', :class => 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/places/auberge.html.erb
<hr> 


<section class="background-gray-lightest">
  <div class="container">
    
      <% @places.each do |place| %>
      <% if place.auberge %>
        <div class="row" >
            <div class="post">
              <div class="col-sm-3">
                <!-- The image carousel -->
                  <%= content_tag :div, class:"carousel slide", id:'myCarousele'+String(place.id), 'data-ride' => "carousel" do %> 
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                      <div class="item active">
                        <%= image_tag place.picture1.url(), class:'img-responsive' %>
                      </div>
                      <% if place.picture2.url()!='house.png' %>
                        <div class="item">
                          <%= image_tag place.picture2.url(), class:'img-responsive' %>
                        </div>
                      <% end %>
                      <% if place.picture3.url()!='house.png' %>
                        <div class="item">
                          <%= image_tag place.picture3.url(), class:'img-responsive' %>
                        </div>
                      <% end %>
                      <% if place.picture4.url()!='house.png' %>
                        <div class="item">
                          <%= image_tag place.picture4.url(), class:'img-responsive' %>
                        </div>
                      <% end %>
                      <% if place.picture5.url()!='house.png' %>
                        <div class="item">
                          <%= image_tag place.picture5.url(), class:'img-responsive' %>
                        </div>
                      <% end %>

                    </div>

                    <!-- Left and right controls -->
                    <%= content_tag :a, class:"left carousel-control", href:'#myCarousele'+String(place.id), 'data-slide' => "prev" do %>
                      <span class="glyphicon glyphicon-chevron-left"></span>
                      <span class="sr-only">Previous</span>
                    <% end %>
                    <%= content_tag :a, class:"right carousel-control", href:'#myCarousele'+String(place.id), 'data-slide' => "next" do %>
                      <span class="glyphicon glyphicon-chevron-right"></span>
                      <span class="sr-only">Next</span>
                    <% end %>
                  <% end %>
              </div>
              <div class="col-sm-9">
                <h3> <%= link_to place.name, place %> </h3>
                <p class="post__intro"> <%= place.description %></p>
                <i class='fa fa-eye' style="color:blue"><%= String(place.views) %> </i> </i class='fa fa-toto'  style="margin-left:5%;">  </i>
                      <i class='fa fa-heart' style="color:indianred;margin-left:5%;"><%= String(place.likes) %></i>
                <p class="read-more"><%= link_to 'Voir en détail', place, class:'btn btn-ghost' %></p>
              </div>
            </div>
         </div>
        <hr> 
      <% end %>
      <% end %>
  </div>









</section>

app/views/places/courtiers.html.erb
<div class="container">
    <%= search_form_for @q, url: courtiers_path, html: { method: :get } do |f| %>
    <div class="form-group has-feedback col-md-12">
    <%= f.label :Rechercher, class:'label label-success' %>
    <%= f.search_field :name_cont, class:'form-control', placeholder:'Cherchez un courtier' %>
    </div>  
    <%= f.check_box :courtier_true, include_hidden: false, checked: true, hidden:true %>
    <div class="form-group col-md-12">
    <%= f.submit 'Rechercher', :class => 'btn btn-primary btn-lg btn-block' %>
    </div>
    <% end %>
</div>


<% @court.each do |c| %>
<% if c.courtier==true %>
<hr>  
<div class="row comment">
        <div class="col-sm-3 col-md-2 text-center-xs">
          <p>
            <%= image_tag c.profile.url(), class:'img-responsive img-circle' %>
          </p>
        </div>
        <div class="col-sm-9 col-md-10">
          <h5><%= c.name %></h5>
          <p class="posted"><i class="fa fa-clock-o"></i> <%= c.created_at.strftime("%d %b. %Y") +" "+ c.created_at.strftime("%H:%M")  %></p>
          <p class="text-gray"><%= c.description %>.</p>
          <p class="reply"><a><i class="fa fa-reply"></i> <label class='label label-info'><%= c.cellNumber %></label></a>
          <a> <label class='label label-primary'><%= c.email %></label></a> 
          <%= link_to 'Voir articles', shop_path(@c, :type => c.id), class:'btn btn-primary' %>
          </p>
        </div>
  </div>
  
<% end %>
<% end %>

app/views/places/edit.html.erb
<h1 align="center">Modifier le logement</h1>

<%= render 'form', place: @place %>

 |

app/views/places/guide.html.erb
<h1>   GUIDE </h1>GUIDE

app/views/places/home.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Categoryname</th>
      <th>Price</th>
      <th>Availability</th>
      <th>Furnitures</th>
      <th>Daily</th>
      <th>Monthly</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.description %></td>
        <td><%= place.categoryName %></td>
        <td><%= place.price %></td>
        <td><%= place.availability %></td>
        <td><%= place.furnitures %></td>
        <td><%= place.daily %></td>
        <td><%= place.monthly %></td>
        <td> <%= image_tag(place.picture1.url(), :size => '200x200') %> </td>
        <td> <%= image_tag(place.picture2.url(), :size => '200x200') %> </td>
        <td> <%= image_tag(place.picture3.url(), :size => '200x200') %> </td>
        <td> <%= image_tag(place.picture4.url(), :size => '200x200') %> </td>
        <td> <%= image_tag(place.picture5.url(), :size => '200x200') %> </td>
        <td><%= place.shared %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<div class="container">   
<h1 align="center">Publier un logement</h1>
<label class='label label-success' align="center">Nouveau Logement</label>

<%= render 'form', place: @place %>


</div>

app/views/places/pubs.html.erb
<br>
<div class="container" align="center">  
  <h1>  Vos Logements</h1>
  <p> Votre espace personnel où vous pouvez consulter tous les logements que vous avez proposés. Le réglement du site vous propose de supprimer 
    les logements que vous avez vendus et de marquer comme indisponibles ceux que vous avez cédés temporairement (location par exemple...)
    Pour plus d'informations, n'hésitez pas à suivre le guide.

  </p>
</div>
<div class="container"> 
    <hr>  
  <h4 align="center">Propriétaire </h4>

  <div class="row comment">
        <div class="col-sm-3 col-md-2 text-center-xs">
          <p>
            <%= image_tag current_user.profile.url(), class:'img-responsive img-circle' %>
          </p>
        </div>
        <div class="col-sm-9 col-md-10">
          <h5><%= current_user.name %></h5>
          <p class="posted"><i class="fa fa-clock-o"></i> <%= current_user.created_at.strftime("%d %b. %Y") +" "+ current_user.created_at.strftime("%H:%M")  %></p>
          <p class="text-gray"><%= current_user.description %>.</p>
          <p class="reply"><a><i class="fa fa-phone"></i> <label class='label label-info'><%= current_user.cellNumber %></label></a></p>
          <p class="reply"><a><i class="fa fa-map-pin"></i> <label class='label label-info'><%= current_user.adress %></label></a></p>
          <p class="reply"><a><i class="fa fa-envelope"></i> <label class='label label-info'><%= current_user.email %></label></a></p>
        </div>
  </div>
  <br>
  <hr>
  <h1 align="center">Logements</h1>
  <br>
    

<section class="background-gray-lightest">
  <div class="container">
    
      <% @pubPlaces.each do |place| %>
        <div class="row" >
            <div class="post">
              <div class="col-sm-3">
                <!-- The image carousel -->
                  <%= content_tag :div, class:"carousel slide", id:'myCarousele'+String(place.id), 'data-ride' => "carousel" do %> 
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                      <div class="item active">
                        <%= image_tag place.picture1.url(), class:'img-responsive' %>
                      </div>
                      <% if place.picture2.url()!='house.png' %>
                        <div class="item">
                          <%= image_tag place.picture2.url(), class:'img-responsive' %>
                        </div>
                      <% end %>
                      <% if place.picture3.url()!='house.png' %>
                        <div class="item">
                          <%= image_tag place.picture3.url(), class:'img-responsive' %>
                        </div>
                      <% end %>
                      <% if place.picture4.url()!='house.png' %>
                        <div class="item">
                          <%= image_tag place.picture4.url(), class:'img-responsive' %>
                        </div>
                      <% end %>
                      <% if place.picture5.url()!='house.png' %>
                        <div class="item">
                          <%= image_tag place.picture5.url(), class:'img-responsive' %>
                        </div>
                      <% end %>

                    </div>

                    <!-- Left and right controls -->
                    <%= content_tag :a, class:"left carousel-control", href:'#myCarousele'+String(place.id), 'data-slide' => "prev" do %>
                      <span class="glyphicon glyphicon-chevron-left"></span>
                      <span class="sr-only">Previous</span>
                    <% end %>
                    <%= content_tag :a, class:"right carousel-control", href:'#myCarousele'+String(place.id), 'data-slide' => "next" do %>
                      <span class="glyphicon glyphicon-chevron-right"></span>
                      <span class="sr-only">Next</span>
                    <% end %>
                  <% end %>
              </div>
              <div class="col-sm-9">
                <h3> <%= link_to place.name, place %> </h3>
                <p class="post__intro"> <%= place.description %></p>
                <p><%= String(place.views) %> <i class='fa fa-eye' style="color:blue"></i> </p>
                <p><%= String(place.likes) %> <i class='fa fa-heart' style="color:indianred"></i> </p>
                <p><%= link_to 'Voir en détail', place, class:'btn btn-success btn-sm' %><%= link_to 'Modifier', edit_place_path(place), class:'btn btn-warning btn-sm' %><%= link_to 'Supprimer', place, class:'btn btn-danger btn-sm', method: :delete, data: { confirm: 'En Êtes vous certain?'}  %></p>
              </div>
            </div>
         </div>
        <hr> 
      <% end %>
  </div>
</section>

</div>

app/views/places/shop.html.erb
<div class="container"> 
    <hr>  
  <h4>Propriétaire </h4>

  <div class="row comment">
        <div class="col-sm-3 col-md-2 text-center-xs">
          <p>
            <%= image_tag @owner.profile.url(), class:'img-responsive img-circle' %>
          </p>
        </div>
        <div class="col-sm-9 col-md-10">
          <h5><%= @owner.name %></h5>
          <p class="posted"><i class="fa fa-clock-o"></i> <%= @owner.created_at.strftime("%d %b. %Y") +" "+ @owner.created_at.strftime("%H:%M")  %></p>
          <p class="text-gray"><%= @owner.description %>.</p>
          <p class="reply"><a><i class="fa fa-reply"></i> <label class='label label-info'><%= @owner.cellNumber %></label></a></p>
          <p class="reply"><a><i class="fa fa-reply"></i> <label class='label label-info'><%= @owner.email %></label></a></p>
        </div>
  </div>
    <section class="background-gray-lightest">
    <div class="container">
        <div class="row">
        <% @ownedPlaces.each do |place| %>
            <div class="col-sm-4">
            <div class="post">
                <div class="image"><%= image_tag place.picture1.url(), class:'img-responsive' %></div>
                <h3> <%= link_to place.name, place %> </h3>
                <p class="post__intro"> <%= place.description %></p>
                <p><%= String(place.views) %> <i class='fa fa-eye' style="color:blue"></i> </p>
                <p><%= String(place.likes) %> <i class='fa fa-heart' style="color:indianred"></i> </p>
                <p class="read-more"><%= link_to 'Voir en détail', place, class:'btn btn-ghost' %></p>
            </div>
            </div>
        <% end %>
        </div>
    </div>
    </section>
</div>

app/views/places/show.html.erb
<script>
  function like(x){
    aa=document.getElementById('aimer');
    bb=document.getElementById('hate');
    b=document.getElementById('hate').childNodes[0];
    a=document.getElementById('aimer').childNodes[0];
    if(true){
      if((a.style!='color:darkcyan;')){
            a.style="color:white;";
            document.getElementById('lll').innerHTML=parseInt(document.getElementById('lll').innerHTML)+1;
            bb.disabled=false;
            
      }else{
        aa.disabled=true;
        aa.visible=true;
      }
    }
  }
  function dislike(x){
    aa=document.getElementById('aimer');
    bb=document.getElementById('hate');
    b=document.getElementById('hate').childNodes[0];
    a=document.getElementById('aimer').childNodes[0];
    if(true){
      if(!(b.style!='color:darkred;')){
            b.style="color:darkred;";
            document.getElementById('lll').innerHTML=parseInt(document.getElementById('lll').innerHTML)-1;
            aa.disabled=false;
            aa.visible=false;
      }else{
        bb.disabled=true;
        bb.visible=true;
      }
    }
  }
</script>
<% if @place.uid!=nil %>
  <% @user =User.find(@place.uid) %>
  <hr>  
  <h4 align="center">Propriétaire </h4>

  <div class="row comment">
        <div class="col-sm-3 col-md-2 text-center-xs">
          <p>
            <%= image_tag @user.profile.url(), class:'img-responsive img-circle' %>
          </p>
        </div>
        <div class="col-sm-9 col-md-10">
          <h5><%= @user.name %></h5>
          <p class="posted"><i class="fa fa-clock-o"></i> <%= @user.created_at.strftime("%d %b. %Y") +" "+ @user.created_at.strftime("%H:%M")  %></p>
          <p class="text-gray"><%= @user.description %>.</p>
          <p class="reply"><a><i class="fa fa-phone"></i> <label class='label label-info'><%= @user.cellNumber %></label></a></p>
          <p class="reply"><a><i class="fa fa-map-pin"></i> <label class='label label-info'><%= @user.adress %></label></a></p>
          <p class="reply"><a><i class="fa fa-envelope"></i> <label class='label label-info'><%= @user.email %></label></a></p>
        </div>
  </div>
<% end %>

<hr>  
<h4 align="center"><%= @place.name %></h4>


          <p>
            <div class="form-group has-feedback col-md-3">
                <!-- The image carousel -->
                  <%= content_tag :div, class:"carousel slide", id:'myCarousele', 'data-ride' => "carousel" do %> 
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                      <div class="item active">
                        <%= image_tag @place.picture1.url(), class:'img-responsive' %>
                      </div>
                      <% if @place.picture2.url()!='house.png' %>
                        <div class="item">
                          <%= image_tag @place.picture2.url(), class:'img-responsive' %>
                        </div>
                      <% end %>
                      <% if @place.picture3.url()!='house.png' %>
                        <div class="item">
                          <%= image_tag @place.picture3.url(), class:'img-responsive' %>
                        </div>
                      <% end %>
                      <% if @place.picture4.url()!='house.png' %>
                        <div class="item">
                          <%= image_tag @place.picture4.url(), class:'img-responsive' %>
                        </div>
                      <% end %>
                      <% if @place.picture5.url()!='house.png' %>
                        <div class="item">
                          <%= image_tag @place.picture5.url(), class:'img-responsive' %>
                        </div>
                      <% end %>

                    </div>

                    <!-- Left and right controls -->
                    <%= content_tag :a, class:"left carousel-control", href:'#myCarousele', 'data-slide' => "prev" do %>
                      <span class="glyphicon glyphicon-chevron-left"></span>
                      <span class="sr-only">Previous</span>
                    <% end %>
                    <%= content_tag :a, class:"right carousel-control", href:'#myCarousele', 'data-slide' => "next" do %>
                      <span class="glyphicon glyphicon-chevron-right"></span>
                      <span class="sr-only">Next</span>
                    <% end %>
                  <% end %>
              </div>
              <div class="form-group has-feedback col-md-9">
                  <blockquote>
                      <i class='fa fa-eye' id='hhh' style="color:blue"><%= String(@place.views) %> </i> </i class='fa fa-toto'  style="margin-left:5%;">  </i>
                      <i class='fa fa-heart' id='lll' style="color:indianred;margin-left:5%;"><%= String(@place.likes) %></i> 
                      <hr>
                      <strong>Description:</strong> <p></p>
                        <p> <%= @place.description %>.</p>
                        <p><strong>Prix: <%= @place.price %> FCFA</strong></p>
                        
                        
                        <hr>
                        <p>
                        <% if @place.availability %>
                          <label class='label label-success'>#Disponible</label>
                        <% end %>
                        <% if @place.furnitures %>
                          <label class='label label-info'>#Meublé</label>
                        <% end %>
                        <% if @place.daily %>
                          <label class='label label-primary'>#Journalier</label>
                        <% end %>
                        <% if @place.monthly %>
                          <label class='label label-primary'>#Mensuel</label>
                        <% end %>
                        <% if @place.shared %>
                          <label class='label label-danger'>#Maison d'Hôtes</label>
                        <% end %>
                        <% if @place.forRent %>
                          <label class='label label-danger'>#A louer</label>
                        <% end %>
                        <% if @place.forSale %>
                          <label class='label label-danger'>#A vendre</label>
                        <% end %>
                        </p>
                      
                 
                  <div> 
                    <% if current_user!=nil %>
                          <% if Aime.exists?(liker: current_user.id, liked: @place.id) %>
                            <%= button_to  place_like_path(@place, :type => @place), method: :get, remote: true, class: 'btn primary', id:'aimer', :onclick => 'like(true)' do %>
                              <i class="fa fa-thumbs-up" style="color:darkcyan;"></i>
                            <% end %>
                          <% else %>
                            <%= button_to  place_like_path(@place, :type => @place), method: :get, remote: true, class: 'btn primary', id:'aimer', :onclick => 'like(false)'  do %>
                              <i class="fa fa-thumbs-up"></i>
                            <% end %>
                          <% end %>
                        <% else %>
                          <%= button_to place_like_path(@place, :type => @place), method: :get, remote: true, class: 'btn primary', id:'aimer', :onclick => 'like(false)' do %>
                            <i class="fa fa-thumbs-up"></i>
                          <% end %>
                        <% end %>
                        <% if current_user!=nil %>
                          <% if Aime.exists?(liker: current_user.id, liked: @place.id) %>
                            <%= button_to  place_dislike_path(@place, :type => @place), method: :get, remote: true, class: 'btn primary', id:'hate', :onclick => 'dislike(true)' do %>
                              <i class="fa fa-thumbs-down"></i>
                            <% end %>
                          <% else %>
                            <%= button_to  place_dislike_path(@place, :type => @place), method: :get, remote: true, class: 'btn primary', id:'hate', :onclick => 'dislike(false)' do %>
                              <i class="fa fa-thumbs-down" style="color:darkred;"></i>
                            <% end %>
                          <% end %>
                        <% else %>
                          <%= button_to  place_dislike_path(@place, :type => @place), method: :get, remote: true, class: 'btn primary', id:'hate', :onclick => 'dislike(false)' do %>
                            <i class="fa fa-thumbs-down" style="color:darkred;"></i>
                          <% end %>
                        <% end %>
                  </div>
                      
                        <% @comms=Comment.where(spot: @place.id) %>
                      <% @comms.each do |co| %>
                        <% @comm_user=User.find(co.talker) %>
                        <% @comm_content = co.speech %>
                        <%= @comm_user.email %> : <%= co.speech %>
                      <% end %>
              </div>
          </p>
<%= simple_form_for Comment.new, :id => "new_comment",:controller => "places",  :action => "save_comments", :remote => true, :class=>'form-control' do |f|  %>
    <%= f.text_area :speech , :class=>'form-control', :style=>"width:50%", :placeholder=>"Dites ce que vous pensez de cet endroit" %>
    <% if current_user!=nil %>
      <%= f.hidden_field(:talker, :value => current_user.id) %>
    <% end %>
    <%= f.hidden_field(:spot, :value => @place.id) %>
    <%= f.submit "Commenter", :class => 'btn btn-primary btn-lg btn-block', :style => 'width:25%' %>
<% end %>
 </blockquote>