config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :aimes
  resources :eyes
  resources :vues
  resources :demandes
  resources :locations
  resources :towns
  root 'places#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :places do
    get :like
    get :dislike
    get :save_comments
  end 
  get 'ventes', to: 'places#ventes'
  get 'rents', to: 'places#locations'
  get 'auberge', to: 'places#auberge'
  get 'shared', to: 'places#shared'
  get 'guide', to: 'places#guide'
  get 'courtiers', to: 'places#courtiers'
  get 'shop', to: 'places#shop'
  get 'pubs', to: 'places#pubs'
  get 'admin', to: 'places#admin'
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
      puts "admin"
    elsif user.id==nil
      #Un guest non connecté
      can [:read, :create], User
      can [:read, :like, :dislike], Place
      can [:read, :create], Demande
      puts "guest"  
    else
      # Un proprio
      can :manage, Place, uid: user.id
      can :create, Place
      can :update, User, id: user.id
      can :read, User
      can [:read, :like, :dislike], Place
      can [:read, :create], Demande
      puts "proprio"
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/aime.rb
class Aime < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/demande.rb
class Demande < ApplicationRecord
end

app/models/eye.rb
class Eye < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
    has_attached_file :picture1, validate_media_type: false, default_url: "house.png"
    has_attached_file :picture2, validate_media_type: false, default_url: "house.png"
    has_attached_file :picture3, validate_media_type: false, default_url: "house.png"
    has_attached_file :picture4, validate_media_type: false, default_url: "house.png"
    has_attached_file :picture5, validate_media_type: false, default_url: "house.png"
    validates_attachment :picture1, :picture2, :picture3, :picture4, :picture5
    do_not_validate_attachment_file_type :picture1, :picture2, :picture3, :picture4, :picture5
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/town.rb
class Town < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]
  has_attached_file :profile, validate_media_type: false, default_url: "default.jpg"
  validates_attachment :profile
  do_not_validate_attachment_file_type :profile


  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.uid = auth.uid
      user.provider = auth.provider
      puts(auth.info.first_name)
      #user.name = auth.info.name    assuming the user model has a name
      #user.image = auth.info.image  assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  
end

app/helpers/aimes_helper.rb
module AimesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/demandes_helper.rb
module DemandesHelper
end

app/helpers/eyes_helper.rb
module EyesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/helpers/vues_helper.rb
module VuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SenVilla</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <script> 
      var width = window.innerWidth
      || document.documentElement.clientWidth
      || document.body.clientWidth;
      windowWidth = width;
    </script>
  </head>

  <body>
    
  
     <!-- navbar-->
      <header class="header">
        <div role="navigation" class="navbar navbar-default">
          <div class="container">
            <div class="navbar-header"><%= link_to 'SenVilla', root_path, class:'navbar-brand' %>
              <div class="navbar-buttons">
                <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle navbar-btn">Menu<i class="fa fa-align-justify"></i></button>
              </div>
            </div>
            <div id="navigation" class="collapse navbar-collapse navbar-right">
              <ul class="nav navbar-nav">
                <li class="inactive"><%= link_to 'Vente', ventes_path %></li>
                <li><%= link_to 'Location', rents_path %></li>
                <li><%= link_to 'Maison d\'Hôtes', shared_path %></li>
                <li><%= link_to 'Auberges', auberge_path %></li>
                <li><%= link_to 'Demandes', demandes_path %></li>
                <li><%= link_to 'Guide', guide_path %></li>
                <% if current_user!=nil %>
                  <li><%= link_to 'Profil', edit_user_registration_path %></li>
                  </ul><%= link_to 'Deconnexion', destroy_user_session_path, :method => :delete, class:'btn navbar-btn btn-ghost' %>
                <% else %>
                  </ul><%= link_to 'Connexion', new_user_session_path, class:'btn navbar-btn btn-ghost' %>
                  </i><%= link_to "<span class=\"glyphicon glyphicon-plus-sign\"></span>Compte".html_safe, new_user_registration_path , class:'btn icon_plus' %>
                <% end %>
              
            </div>
          </div>
        </div>
      </header>
      <% unless controller_name=="sessions" || controller_name=="registrations" %>
            <!-- The menu carousel -->
    
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <!-- Wrapper for slides -->
              <div class="carousel-inner">
                <div class="item active">
                  <%= image_tag 'jumbotron5.jpg' %>
                </div>

                <div class="item">
                  <%= image_tag 'jumbotron6.jpg' %>
                </div>

                <div class="item">
                  <%= image_tag 'jumbotron7.jpg' %>
                </div>
              </div>

              <!-- Left and right controls -->
              <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
              </a>
              <div class="carrcont">
                <h1 style="font-weight: 1400;color:#FFFFFF;font-size:70px">SenVilla</h1>
                <p class="margin-bottom" style="font-weight: 1400;color:#FFFFFF;font-size:20px">Trouvez le logement de vos rêves au Sénégal</p>
                <p><%= link_to 'Courtiers', courtiers_path, class:'btn btn-white', style: 'color:#FFFFFF; background:#222222;' %>
                  <%= link_to 'Publier Logement', new_place_path, class:'btn btn-white', style: 'color:#FFFFFF; background:#222222;' %>
                  <% if current_user!=nil %>
                  <%= link_to 'Mes logements', pubs_path, class:'btn btn-white', style: 'color:#FFFFFF; background:#222222' %>
                  <% end %>
                  <% if current_user!=nil  and current_user.has_role? :admin %>
                  <%= link_to 'Administration', admin_path, class:'btn btn-white', style: 'color:#FFFFFF; background:#111144; opacity:50%' %>
                  <% end %>
                  </p>
              </div>
            </div>



<%end%>

    <%= yield %>
<% unless controller_name=="sessions" || controller_name=="registrations" %>
    <footer class="footer">
      <div class="footer__block">
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-sm-12">
              <h4 class="heading">SenVilla</h4>
              <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus magna. Cras in mi at felis aliquet congue.  Vivamus magna. Cras in mi at felis aliquet congue.</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in mi at felis aliquet congue. </p>
            </div>
            <div class="col-md-4 col-sm-12">
              <h4 class="heading">Nos bureaux</h4>
              <h5>Saint Louis</h5>
              <p> Donec eleifend<br />libero at sagittis<br />mollis + 44 2556 789 8799</p>
              <h5>Dakar</h5>
              <p> Donec eleifend<br />libero at sagittis<br />mollis + 41 2556 789 8799</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-6">
              <h4 class="heading">Nos domaines d'expertise</h4>
              <ul>
                <li><a href="category.html">Location courtage</a></li>
                <li><a href="category.html">Audit conseil</a></li>
                <li><a href="category.html">Support</a></li>
              </ul>
            </div>
            <div class="col-md-4 col-sm-6">
              <h4 class="heading">Suivez nous</h4>
              <p class="social social--big"><a href="#" data-animate-hover="pulse" class="external facebook"><i class="fa fa-facebook"></i></a><a href="#" data-animate-hover="pulse" class="external gplus"><i class="fa fa-google-plus"></i></a><a href="#" data-animate-hover="pulse" class="external twitter"><i class="fa fa-twitter"></i></a><a href="#" data-animate-hover="pulse" class="email"><i class="fa fa-envelope"></i></a></p>
            </div>
            <div class="col-md-4 col-sm-12">
              <h4 class="heading">Tirage au sort</h4>
              <p>Saisissez votre adresse mail et tentez de remporter chaque mois un mois de location gratuit</p>
              <form class="footer__newsletter">
                <div class="input-group">
                  <input type="text" placeholder="Enter your email address" class="form-control"><span class="input-group-btn">
                    <button type="button" class="btn btn-default"><i class="fa fa-send"></i></button></span>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="footer__copyright">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <p>&copy;2017 SenVilla</p>
            </div>
            <div class="col-md-6">
              <p class="credit"><a href="https://bootstrapious.com/e-commerce-templates" class="external">Bootstrapious</a></p>
              <!-- Please do not remove the backlink to us unless you support us at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
            </div>
          </div>
        </div>
      </div>
    </footer>
    <%end%>
  </body>
</html>